from models import FormField


form_fields = [
    FormField(
        id="fullName",
        label="Полное имя",
        name="fullName",
        type="text",
        placeholder="Введите полное имя",
    ),
    FormField(
        id="fullNameGenitive",
        label="Полное имя в винительном падеже. Мы попробовали угадать за вас 😉",
        name="fullNameGenitive",
        type="text",
        placeholder="Введите полное имя в род. падеже",
    ),
    FormField(
        id="parentFullName",
        label="Полное имя родителя",
        name="parentFullName",
        type="text",
        placeholder="Введите полное имя родителя",
        default_value="",
    ),
    FormField(
        id="parentAddress",
        label="Адрес родителя",
        name="parentAddress",
        type="text",
        placeholder="Введите адрес родителя",
        default_value="",
    ),
    FormField(
        id="email",
        label="Email",
        name="email",
        type="email",
        placeholder="example@example.com",
        default_value="",
    ),
    FormField(
        id="parentEmail",
        label="Email родителя",
        name="parentEmail",
        type="email",
        placeholder="parent@example.com",
    ),
    FormField(
        id="school",
        label="Школа",
        name="school",
        type="text",
        placeholder="Введите название школы",
    ),
    FormField(
        id="schoolClass",
        label="Класс",
        name="schoolClass",
        type="number",
        placeholder="Укажите класс",
    ),
    FormField(
        id="birthDate",
        label="Дата рождения",
        name="birthDate",
        type="text",
        placeholder="ДД.ММ.ГГГГ",
    ),
    FormField(
        id="birthPlace",
        label="Место рождения",
        name="birthPlace",
        type="text",
        placeholder="Место рождения",
        default_value="",
    ),
    FormField(
        id="phone",
        label="Ваш телефон",
        name="phone",
        type="text",
        placeholder="Введите ваш номер телефона",
        default_value="",
    ),
    FormField(
        id="parentPhone",
        label="Телефон родителя",
        name="parentPhone",
        type="text",
        placeholder="Введите номер телефона родителя",
        default_value="",
    ),
]
