from models import FormField


form_fields = [
    FormField(
        id="fullName",
        label="Полное имя",
        name="fullName",
        type="text",
        placeholder="Введите полное имя",
    ),
    FormField(
        id="fullNameGenitive",
        label="Полное имя в винительном падеже. Мы попробовали угадать за вас 😉",
        name="fullNameGenitive",
        type="text",
        placeholder="Введите полное имя в род. падеже",
    ),
    FormField(
        id="parentFullName",
        label="Полное имя родителя",
        name="parentFullName",
        type="text",
        placeholder="Введите полное имя родителя",
        default_value="",
        required=False,
    ),
    FormField(
        id="parentBirthDate",
        label="Дата рождения родителя",
        name="parentBirthDate",
        type="text",
        placeholder="27.10.1977",
        default_value="",
        required=False,
        extraInputClasses="datepicker",
    ),
    FormField(
        id="parentAddress",
        label="Адрес родителя",
        name="parentAddress",
        type="text",
        placeholder="Введите адрес родителя",
        default_value="",
        required=False,
    ),
    FormField(
        id="email",
        label="Email",
        name="email",
        type="email",
        placeholder="example@example.com",
        default_value="",
    ),
    FormField(
        id="parentEmail",
        label="Email родителя",
        name="parentEmail",
        type="email",
        placeholder="parent@example.com",
        required=False,
    ),
    FormField(
        id="school",
        label="Образовательная организация (если есть)",
        name="school",
        type="text",
        placeholder="Школа №1",
        required=False,
    ),
    FormField(
        id="schoolClass",
        label="Класс образовательной организации (если есть)",
        name="schoolClass",
        type="number",
        placeholder="10",
        required=False,
    ),
    FormField(
        id="birthDate",
        label="Дата рождения",
        name="birthDate",
        type="text",
        placeholder="ДД.ММ.ГГГГ",
        extraInputClasses="datepicker",
    ),
    FormField(
        id="birthPlace",
        label="Место рождения",
        name="birthPlace",
        type="text",
        placeholder="Место рождения",
        default_value="",
    ),
    FormField(
        id="phone",
        label="Ваш телефон",
        name="phone",
        type="text",
        placeholder="+7 ...",
        default_value="",
        extraInputClasses="input-phone",
    ),
    FormField(
        id="parentPhone",
        label="Телефон родителя",
        name="parentPhone",
        type="text",
        placeholder="+7 ...",
        default_value="",
        extraInputClasses="input-phone-2",
        required=False,
    ),
]
